apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jmeter.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  data.csv: {{ .Values.data | b64enc | quote }}
  test.jmx: {{ .Values.testfile | b64enc | quote }}
